nameOverride: "vector-agent"
fullnameOverride: "vector-agent"

role: "Agent"

resources:
  requests:
    cpu: 20m
    memory: 50Mi
  limits:
    cpu: 200m
    memory: 256Mi

customConfig:
  data_dir: /vector-data-dir

  sources:
    kubernetes_logs:
      type: kubernetes_logs
      glob_minimum_cooldown_ms: 5000

  sinks:
    vector_aggregator:
      type: vector
      inputs:
        - kubernetes_logs
      address: vector-aggregator:6000

rollWorkload: true

rbac:
  create: true

serviceAccount:
  create: true

podAnnotations:
  prometheus.io/scrape: "true"
  prometheus.io/port: "8686"

tolerations:
  - effect: NoExecute
    operator: Exists
  - effect: NoSchedule
    operator: Exists
